nlpservice:
  image: slidewiki/nlpservice:latest-dev
  restart: on-failure:5
  expose:
    - "9000"
  environment:
    - APPLICATION_SECRET=sndv9sd98adpvnaa0wefe0fa04nvpdnvp9e+-.sfw03fs
    - VIRTUAL_HOST=nlpservice.experimental.slidewiki.org
    - SERVICE_URL_DECK="deckservice.experimental.slidewiki.org"
    - SERVICE_URL_NLPSTORE="nlpstore.experimental.slidewiki.org"
    - LETSENCRYPT_HOST=nlpservice.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
